services:
  - type: web
    name: booksearch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --worker-class sync --log-level info --access-logfile - --error-logfile -
    envVars:
      - key: FLASK_DEBUG
        value: False
      - key: PYTHONUNBUFFERED
        value: 1

